[theme]
base = "dark"
backgroundColor = "#07080a"
secondaryBackgroundColor = "#0e1015"
textColor = "#d4daf0"
font = "monospace"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
